### PR TITLE
Using a TextBlock in Titlebar instead of Label

### PR DESCRIPTION
**Pull request by Simnico99**
…cted by other Library

### CODE REVIEW

**Comment by nlogozzo** [comment]
Oops looks like we did it at the same time 🤦 #11

**Comment by Simnico99** [comment]
> Oops looks like we did it at the same time 🤦 #11

Haha I will include yours I guess it will add you in the collaborators

**Comment by nlogozzo** [comment]
Oops I just closed it haha. We're racing against the clock. I reopened it. Thanks!

**Comment by Simnico99** [comment]
Published 3.0.9 Will be ready on NuGet Soon

**Pull request closed without merging**
